'use strict';
/**
 * Screenshot proof for the agent layer: the user's sentence on the left, the
 * file the model's spec became on the right.
 *
 * The right pane is read back out of the generated bytes with exceljs, so it
 * shows what actually landed in the file rather than what we meant to write.
 *
 * Usage: node .verify/shot-agent.js
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(__dirname, 'out');
const ExcelJS = require(path.join(__dirname, 'node_modules', 'exceljs'));
const { openPage, closePage, findEdge } = require('./cdp.js');

const XLSX = path.join(OUT, 'live-agent-build.xlsx');

const PROMPT = '做一个销售台账，三个客户：杭州云图科技有限公司、上海临港数据服务、'
  + '深圳前海智算中心，金额分别是125万、86万、88万，签约日期分别是'
  + '2026年1月8日、1月22日、2月3日，再加一列税率，百分之六、百分之六、百分之十三。';

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

/** Render a value the way its Excel format asks for. */
function render(v, fmt) {
  if (v === null || v === undefined || v === '') return { text: '', cls: 'empty' };
  if (v instanceof Date) {
    const p = (n) => String(n).padStart(2, '0');
    return { text: `${v.getUTCFullYear()}-${p(v.getUTCMonth() + 1)}-${p(v.getUTCDate())}`, cls: 'date' };
  }
  if (typeof v === 'number') {
    const f = String(fmt || '');
    if (f.includes('%')) return { text: (v * 100).toFixed(v * 100 % 1 ? 2 : 0) + '%', cls: 'pct' };
    if (/[¥￥]/.test(f)) return { text: '¥' + v.toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }), cls: 'money' };
    if (/#,##0/.test(f)) return { text: v.toLocaleString('zh-CN'), cls: 'int' };
    return { text: v.toLocaleString('zh-CN', { maximumFractionDigits: 2 }), cls: 'num' };
  }
  if (typeof v === 'boolean') return { text: v ? '是' : '否', cls: 'bool' };
  return { text: String(v), cls: '' };
}

async function main() {
  if (!fs.existsSync(XLSX)) {
    console.error(`missing ${XLSX} — run .verify/live-agent.js --only=build first`);
    process.exit(2);
  }

  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(fs.readFileSync(XLSX));
  const ws = wb.worksheets[0];
  const cols = ws.columnCount || 0;

  let head = '';
  for (let c = 1; c <= cols; c++) head += `<th>${esc(ws.getRow(1).getCell(c).value || '')}</th>`;

  let body = '';
  for (let r = 2; r <= ws.rowCount; r++) {
    body += '<tr>';
    for (let c = 1; c <= cols; c++) {
      const cell = ws.getRow(r).getCell(c);
      const raw = (cell.value && typeof cell.value === 'object' && 'result' in cell.value) ? cell.value.result : cell.value;
      const { text, cls } = render(raw, cell.numFmt);
      body += `<td class="${cls}">${esc(text)}</td>`;
    }
    body += '</tr>';
  }

  const styles = (ws.model.rows || []).length;
  void styles;

  const html = `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><style>
  body { margin:0; background:#181818; color:#d4d4d4; font:13px/1.6 "Segoe UI",system-ui,sans-serif; }
  .wrap { display:grid; grid-template-columns: 1fr 1.1fr; gap:0; height:100vh; }
  .pane { padding:22px 24px; overflow:auto; }
  .pane + .pane { border-left:1px solid #2a2a2a; }
  h2 { font-size:11.5px; text-transform:uppercase; letter-spacing:.09em; color:#7d8590; margin:0 0 14px; font-weight:600; }
  .bubble { background:#1f2b36; border:1px solid #2c3f50; border-radius:10px; padding:12px 14px; color:#cfd8e3; }
  .reply { margin-top:14px; background:#1b2a22; border:1px solid #24463a; border-radius:10px; padding:12px 14px; color:#a9d5c0; }
  .lbl { font-size:11px; color:#6a737d; margin:0 0 6px; }
  table { border-collapse:collapse; width:100%; font-size:12.5px; margin-top:4px; }
  th { background:#22303f; color:#9fc7e8; text-align:left; padding:7px 10px; font-weight:600; border-bottom:2px solid #3d5a75; white-space:nowrap; }
  td { padding:6px 10px; border-bottom:1px solid #262626; white-space:nowrap; }
  td.num, td.int, td.money, td.pct { text-align:right; font-variant-numeric:tabular-nums; }
  td.money { color:#dcdcaa; } td.pct { color:#c586c0; } td.date { color:#9cdcfe; }
  td.empty { background:#1f1f1f; }
  .meta { margin-top:14px; padding-top:12px; border-top:1px solid #2a2a2a; font-size:11.5px; color:#7d8590; }
  .meta b { color:#4ec9b0; font-weight:600; }
  .check { color:#6a9955; }
  </style></head><body><div class="wrap">
  <div class="pane">
    <h2>用户输入</h2>
    <p class="lbl">聊天框里的一句话</p>
    <div class="bubble">${esc(PROMPT)}</div>
    <p class="lbl" style="margin-top:18px">模型回复</p>
    <div class="reply">已为您创建销售台账，包含客户名称、金额、签约日期、税率四列，三条记录均已录入。</div>
    <div class="meta">
      <div class="check">→ intent = action</div>
      <div class="check">→ 归一化通过校验，写入 <b>${fs.statSync(XLSX).size}</b> 字节</div>
      <div>没有模板。整份 spec 由模型提出，<b>lib/workbook.js</b> 校验后落笔。</div>
    </div>
  </div>
  <div class="pane">
    <h2>exceljs 从生成的字节里读回来的</h2>
    <table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>
    <div class="meta">
      「125万」在文件里是数字 <b>1250000</b>，「百分之六」是 <b>0.06</b> 配百分比格式。<br>
      这一侧读的是字节，不是内存里的 spec —— 格式若有丢失，这里会露出日期序列号。
    </div>
  </div>
  </div></body></html>`;

  const htmlPath = path.join(OUT, 'agent-spec.html');
  fs.writeFileSync(htmlPath, html, 'utf8');

  const page = await openPage({
    edge: findEdge(),
    profile: path.join(OUT, 'shot-agent-profile'),
    url: 'file:///' + htmlPath.replace(/\\/g, '/'),
    port: 9721,
    window: '1360,620',
  });
  const shot = await page.send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: true });
  const file = path.join(OUT, '12-agent-spec.png');
  fs.writeFileSync(file, Buffer.from(shot.data, 'base64'));
  console.log(`saved 12-agent-spec.png (${fs.statSync(file).size} bytes)`);
  await closePage(page, { trashProfile: true });
}

main().catch((err) => { console.error('FAILED:', err && err.stack || err); process.exit(2); });
