'use strict';
/**
 * Build the single-file desktop executable.
 *
 * Pipeline:
 *   0. compile TypeScript into .build/js/ (tools/build-js.js)
 *   1. bundle desktop.js + lib/*.js into one CommonJS script
 *      (a packaged executable's own require resolves builtins only, so the
 *      graph must be joined before it is embedded)
 *   2. embed public/ as SEA assets
 *   3. write the sea-config manifest
 *   4. generate the preparation blob with node --experimental-sea-config
 *   5. copy node.exe and inject the blob with postject
 *
 * Step 0 runs first and is not optional: modules are authored in TypeScript,
 * so the bundler's inputs do not exist on disk until they are compiled. It
 * writes `.build/js/` rather than compiling in memory so that "what actually
 * got bundled" stays inspectable — see NOTES.md #40 on build products drifting
 * from their source.
 *
 * Output: dist/TabAgent.exe
 *
 * Usage:
 *   node tools/build-exe.js [--out dist/TabAgent.exe] [--skip-inject]
 */

const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { execFileSync } = require('node:child_process');
const { collectModules, renderBundle, externalSpecs } = require('./bundle');

const ROOT = path.join(__dirname, '..');
const PUBLIC_DIR = path.join(ROOT, 'public');
const WORK_DIR = path.join(ROOT, '.build');
const JS_DIR = path.join(WORK_DIR, 'js');
const DIST_DIR = path.join(ROOT, 'dist');

const FUSE = 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2';
const BLOB_NAME = 'NODE_SEA_BLOB';

function parseArgs(argv) {
  const out = { out: path.join(DIST_DIR, 'TabAgent.exe'), skipInject: false, keepWork: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out') out.out = path.resolve(argv[++i]);
    else if (a.startsWith('--out=')) out.out = path.resolve(a.slice(6));
    else if (a === '--skip-inject') out.skipInject = true;
    else if (a === '--keep-work') out.keepWork = true;
  }
  return out;
}

function step(n, label) {
  console.log(`\n[${n}] ${label}`);
}

/** Every servable file under public/, as {key, abs}. */
function publicAssets() {
  const out = [];
  (function walk(dir, prefix) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, entry.name);
      const key = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(abs, key);
      else if (entry.isFile()) out.push({ key, abs });
    }
  })(PUBLIC_DIR, '');
  return out.sort((a, b) => a.key.localeCompare(b.key));
}

function main() {
  const args = parseArgs(process.argv.slice(2));

  fs.mkdirSync(WORK_DIR, { recursive: true });
  fs.mkdirSync(path.dirname(args.out), { recursive: true });

  step(0, 'compile TypeScript');
  // Run as a child process rather than requiring it, so the build step keeps
  // its own CLI contract (and its --check mode stays usable on its own).
  execFileSync(process.execPath, ['--no-warnings', path.join(__dirname, 'build-js.js')], {
    stdio: 'inherit',
    cwd: ROOT,
  });

  step(1, 'bundle modules');
  // Bundle from the STRIPPED tree: lib/*.js live there, not next to the .ts.
  const { modules, entryId } = collectModules(path.join(JS_DIR, 'desktop.js'));
  const externals = [...externalSpecs(modules)].sort();
  const thirdParty = externals.filter((s) => !s.startsWith('node:'));
  if (thirdParty.length) {
    throw new Error('refusing to bundle third-party modules: ' + thirdParty.join(', '));
  }
  console.log(`    ${modules.length} modules, externals: ${externals.join(', ')}`);
  const banner = [
    '// Generated by tools/build-exe.js. Do not edit.',
    `// bundled modules: ${modules.length}`,
  ].join('\n');
  const bundleCode = renderBundle(modules, { entryId, banner });
  const bundlePath = path.join(WORK_DIR, 'bundle.js');
  fs.writeFileSync(bundlePath, bundleCode);
  console.log(`    bundle.js = ${bundleCode.length} bytes`);

  step(2, 'embed public/ assets');
  const assets = publicAssets();
  // public/package.json exists only to mark the directory as ESM for Node's
  // import graph check. It is not served, so it is not embedded.
  const embeddable = assets.filter((a) => a.key !== 'package.json');
  console.log(`    ${embeddable.length} files: ${embeddable.map((a) => a.key).join(', ')}`);

  step(3, 'write sea-config manifest');
  const manifest = {
    main: bundlePath,
    output: path.join(WORK_DIR, 'sea-prep.blob'),
    disableExperimentalSEAWarning: true,
    useSnapshot: false,
    useCodeCache: false,
    assets: Object.fromEntries(embeddable.map((a) => [a.key, a.abs])),
  };
  const manifestPath = path.join(WORK_DIR, 'sea-config.json');
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
  console.log(`    ${manifestPath}`);

  step(4, 'generate preparation blob');
  execFileSync(process.execPath, ['--experimental-sea-config', manifestPath], {
    stdio: 'inherit',
    cwd: WORK_DIR,
  });
  const blobPath = manifest.output;
  const blobSize = fs.statSync(blobPath).size;
  console.log(`    sea-prep.blob = ${blobSize} bytes`);

  step(5, 'copy node.exe and inject');
  fs.copyFileSync(process.execPath, args.out);
  console.log(`    carrier = ${(fs.statSync(args.out).size / 1024 / 1024).toFixed(1)} MB`);

  if (args.skipInject) {
    console.log('    --skip-inject: stopping before postject (carrier is a bare node.exe)');
    return;
  }

  const cli = resolvePostject();
  console.log(`    postject = ${cli}`);
  execFileSync(process.execPath, [cli, args.out, BLOB_NAME, blobPath, '--sentinel-fuse', FUSE], {
    stdio: 'inherit',
  });

  const finalSize = fs.statSync(args.out).size;
  console.log(`\ndone: ${args.out}`);
  console.log(`      ${(finalSize / 1024 / 1024).toFixed(1)} MB`);

  if (!args.keepWork) {
    // Keep the work directory: bundle.js is useful when debugging a build.
    console.log(`      intermediates in ${WORK_DIR}`);
  }
}

/** Locate postject, preferring a local install. */
function resolvePostject() {
  const local = path.join(ROOT, 'node_modules', 'postject', 'dist', 'cli.js');
  if (fs.existsSync(local)) return local;
  try {
    const globalRoot = execFileSync('npm.cmd', ['root', '-g'], { encoding: 'utf8' }).trim();
    const globalCli = path.join(globalRoot, 'postject', 'dist', 'cli.js');
    if (fs.existsSync(globalCli)) return globalCli;
  } catch { /* fall through to the error below */ }
  throw new Error(
    'postject not found. Install it first:\n' +
    '  npm install postject --strict-ssl=false --no-audit --no-fund',
  );
}

main();
